// <auto-generated />
namespace Said.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class _20160814225347 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20160814225347));
        
        string IMigrationMetadata.Id
        {
            get { return "201608141459433_20160814225347"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
