// <auto-generated />
namespace Said.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class test20160803232118 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test20160803232118));
        
        string IMigrationMetadata.Id
        {
            get { return "201608031521303_test20160803232118"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
