//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Said.Domain.Said.Services.Said.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classify
    {
        public int ClassifyId { get; set; }
        public int CCount { get; set; }
        public string CIcon { get; set; }
        public string CLastBlogId { get; set; }
        public string CLastBlogName { get; set; }
        public string CName { get; set; }
        public int IsDel { get; set; }
    }
}
