//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Said.Domain.Said.Services.Said.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Said
    {
        public string SaidId { get; set; }
        public string SXML { get; set; }
        public string STitle { get; set; }
        public string STag { get; set; }
        public string SSummaryTrim { get; set; }
        public string SSummary { get; set; }
        public int SSongId { get; set; }
        public string SScript { get; set; }
        public int SReprint { get; set; }
        public int SPV { get; set; }
        public string SName { get; set; }
        public string SLastCommentUser { get; set; }
        public string SLastComment { get; set; }
        public Nullable<int> SIsTop { get; set; }
        public string SImgTrim { get; set; }
        public string SImg { get; set; }
        public string SHTML { get; set; }
        public System.DateTime SDate { get; set; }
        public string SCSS { get; set; }
        public string SContext { get; set; }
        public int SComment { get; set; }
        public int SClick { get; set; }
        public Nullable<int> SClassifyId { get; set; }
        public int IsDel { get; set; }
    }
}
