//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Said.Domain.Said.Services.Said.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int SongId { get; set; }
        public string SongUrl { get; set; }
        public string SongName { get; set; }
        public Nullable<int> SongLikeCount { get; set; }
        public string SongImg { get; set; }
        public string SongArtist { get; set; }
        public string SongAlbum { get; set; }
        public int IsDel { get; set; }
    }
}
